config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :accidents
  resources :drivers
  root :to => 'home#index'

  get "home/index"

  resources :photos, only: [:new, :create, :index, :destroy]
  root to: 'photos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accident.rb
class Accident < ApplicationRecord
  validates_presence_of :accident_type, :time, :car_id
  has_one :cars
end

app/controllers/accidents_controller.rb
class AccidentsController < ApplicationController
  before_action :set_accident, only: [:show, :edit, :update, :destroy]

  # GET /accidents
  # GET /accidents.json
  def index
    @accidents = Accident.all
  end

  # GET /accidents/1
  # GET /accidents/1.json
  def show
  end

  # GET /accidents/new
  def new
    @accident = Accident.new
  end

  # GET /accidents/1/edit
  def edit
  end

  # POST /accidents
  # POST /accidents.json
  def create
    @accident = Accident.new(accident_params)

    respond_to do |format|
      if @accident.save
        format.html { redirect_to @accident, notice: 'Accident was successfully created.' }
        format.json { render :show, status: :created, location: @accident }
      else
        format.html { render :new }
        format.json { render json: @accident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accidents/1
  # PATCH/PUT /accidents/1.json
  def update
    respond_to do |format|
      if @accident.update(accident_params)
        format.html { redirect_to @accident, notice: 'Accident was successfully updated.' }
        format.json { render :show, status: :ok, location: @accident }
      else
        format.html { render :edit }
        format.json { render json: @accident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accidents/1
  # DELETE /accidents/1.json
  def destroy
    @accident.destroy
    respond_to do |format|
      format.html { redirect_to accidents_url, notice: 'Accident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accident
      @accident = Accident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accident_params
      params.require(:accident).permit(:time, :accident_type, :car_id)
    end
end

app/helpers/accidents_helper.rb
module AccidentsHelper
end

app/views/accidents/_form.html.erb
<%= form_with(model: accident, local: true) do |form| %>
  <% if accident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accident.errors.count, "error") %> prohibited this accident from being saved:</h2>

      <ul>
      <% accident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time, id: :accident_time %>
  </div>

  <div class="field">
    <%= form.label :accident_type %>
    <%= form.text_field :accident_type, id: :accident_type %>
  </div>

  <div class="field">
    <%= form.label :car_id %><br/>
    <%= form.select :car_id, options_for_select(Car.all.map{|s|[s.id.to_s + " " + s.car_type + " " + s.model]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accidents/edit.html.erb
<h1>Editing Accident</h1>

<%= render 'form', accident: @accident %>

<%= link_to 'Show', @accident %> |
<%= link_to 'Back', accidents_path %>

app/views/accidents/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Accident</h1>
  <br>
  <%= link_to "Home", root_path, :class => "btn btn-success" %>
  <br>
  <br>
  <% @accidents.each do |accident| %>
    <div class="item-details">
      <div class="item-description">
        <%= accident.time %>
      </div>
      <div class="item-description">
        <%= accident.accident_type %>
      </div>
      <div class="item-description">
        <%= get_car_info(accident.car_id) %>
      </div>
      <div class="action-items">
        <div>
          <%= link_to "Edit", edit_accident_path(accident), :class => "btn btn-success"%>
        </div>
        <div>
          <%= button_to "Delete", accident, :class => "btn btn-success", :method => :delete, data: { confirm: 'Are you sure?' }  %>
        </div>
      </div>
    </div>
  <% end %>
  <br>
  <br>
  <%= link_to 'New Accident', new_accident_path, :class => "btn btn-success" %>
</div>

app/views/accidents/new.html.erb
<h1>New Accident</h1>

<%= render 'form', accident: @accident %>

<%= link_to 'Back', accidents_path %>

app/views/accidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @accident.time %>
</p>

<p>
  <strong>Type:</strong>
  <%= @accident.accident_type %>
</p>

<p>
  <strong>Car Id:</strong>
  <%= @accident.car_id %>
</p>

<%= link_to 'Edit', edit_accident_path(@accident) %> |
<%= link_to 'Back', accidents_path %>