config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :accidents
  resources :drivers
  root :to => 'home#index'

  get "home/index"

  resources :photos, only: [:new, :create, :index, :destroy]
  root to: 'photos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_attached_file :image
  validates_presence_of :image
  validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"]}
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.order('created_at')
  end

  def new
    @photo = Photo.new
  end

  def create
    puts "In create photo"
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "The photo was added!"
    else
      render 'new'
    end
  end

  private

   def photo_params
     params.require(:photo).permit(:image, :title)
   end
 end

app/views/photos/_edit.html.erb
<h1>Editing Photo</h1>

<%= render 'new', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/_new.html.erb
<%= form_for @photo do |f| %>
  <%= render 'shared/errors', object: @photo %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

app/views/photos/_photo.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= photo.title %></h4>
  </div>
</div>

app/views/photos/index.html.erb
<div class="page-header"><h1>Photos</h1></div>

<%= render @photos %>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>
 <%= render 'new', object: @photo %>