config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :accidents
  resources :drivers
  root :to => 'home#index'

  get "home/index"

  resources :photos, only: [:new, :create, :index, :destroy]
  root to: 'photos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  validates_presence_of :model, :car_type, :color, :photo_id, :year
  has_many :accidents
  has_one :drivers

  before_destroy :destroy_drivers_and_accidents

   private

   def destroy_drivers_and_accidents()
     Accident.where(car_id: self.id).destroy_all
     Driver.where(car_id: self.id).destroy_all
   end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
    @photo = Photo.new
  end

  # GET /cars/1/edit
  def edit
    if (@car.photo_id.nil?)
      @photo = Photo.new
    else
      @photo = Photo.find(@car.photo_id)
    end
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        @car.photo_id = @photo.id
        if @car.save
          format.html { redirect_to @car, notice: 'Car was successfully created.' }
          format.json { render :show, status: :created, location: @car }
        else
          format.html { render :new }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        @car.photo_id = @photo.id
        if @car.update(car_params)
          format.html { redirect_to @car, notice: 'Car was successfully updated.' }
          format.json { render :show, status: :ok, location: @car }
        else
          format.html { render :edit }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:color, :year, :model, :car_type, :photo_id)
    end

    # Allows photos to be uploaded through the car controller
    def photo_params
      params.require(:car).permit(:image)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
  def get_photos(id)
    if (id.nil?)
      @photo = Photo.first
    else
      @photo = Photo.find(id)
    end
  end
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :car_color %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :car_year %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :car_type %>
    <%= form.text_field :car_type, id: :car_car_type %>
  </div>


  <div class="field">
      <%= form.label :car_photo_id %>
      <%= render 'shared/errors', object: @photo %>
      <% if !@photo.id.nil? %>
        <div class="photo-image">
          <%= render @photo %>
        </div>
      <% end %>
      <div class="form-group">

        <%= form.file_field :image, class: 'form-control'%>
      </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="container">
    <h1>Cars</h1>
    <br>
    <%= link_to "Home", root_path, :class => "btn btn-success" %>
    <br>
      <div id="products" class="row list-group">
        <% @cars.each do |car| %>
          <div class="item-details">
            <div class="photo-image">
                <img class="group list-group-image">
                  <%= render get_photos(car.photo_id) %>
                </img>
            </div>
            <div class="item-description">
                <h4 class="group inner list-group-item-heading">
                    Car <% car.id.to_s %> </h4>
                <p class="group inner list-group-item-text">
                  <%= car.year.to_s + " " + car.car_type + " " + car.model + " " + car.color %></p>
             </div>
            <div class="action-items">
              <div>
                <%= link_to "Edit", edit_car_path(car), :class => "btn btn-success"%>
              </div>
              <div>
                <%= button_to "Delete", car, :class => "btn btn-success", :method => :delete, data: { confirm: 'Are you sure?' }  %>
              </div>
            </div>
          </div>
          <% end %>
      </div>
      <br>
      <br>
      <%= link_to 'New Car', new_car_path, :class => "btn btn-success" %>
  </div>
</div>

app/views/cars/new.html.erb
<h1>New Car</h1>


<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Car type:</strong>
  <%= @car.car_type %>
</p>

<div class="photo-image">
    <strong>Car Picture:</strong>
    <%= render get_photos(@car.photo_id) %>
</div>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>